#!/bin/bash

INO_PORT=/dev/redboard0
INO_CPU=uno

V=$HOME/arduino-1.0.5/
V=$HOME/arduino-1.6.5/
V=$HOME/arduino-1.5.8/
DIR=ino-$1

mkdir -p $DIR/src $DIR/lib
[ ! -h $DIR/lib/Gameduino2 ] && ln -s ~/Arduino/libraries/Gameduino2 $DIR/lib
cp $1.ino $DIR/src/
cp converted-assets/${1}_assets.h $DIR/src/
cd $DIR &&

ano build -m $INO_CPU --arduino-dist $V || exit
ano upload -m $INO_CPU --arduino-dist $V -p $INO_PORT
