#define LOAD_ASSETS()  GD.safeload("night1.gd2");
#define BACKGROUND_COLOR_HANDLE 0
#define BACKGROUND_COLOR_WIDTH 120
#define BACKGROUND_COLOR_HEIGHT 68
#define BACKGROUND_COLOR_CELLS 2
#define BACKGROUND_BITS_HANDLE 1
#define BACKGROUND_BITS_WIDTH 480
#define BACKGROUND_BITS_HEIGHT 272
#define BACKGROUND_BITS_CELLS 2
#define DEFENSOR_FRONT_HANDLE 2
#define DEFENSOR_FRONT_WIDTH 104
#define DEFENSOR_FRONT_HEIGHT 64
#define DEFENSOR_FRONT_CELLS 2
#define DEFENSOR_TURRET_HANDLE 3
#define DEFENSOR_TURRET_WIDTH 38
#define DEFENSOR_TURRET_HEIGHT 50
#define DEFENSOR_TURRET_CELLS 1
#define DEFENSOR_TURRET_SIZE 50
#define MISSILE_A_HANDLE 4
#define MISSILE_A_WIDTH 17
#define MISSILE_A_HEIGHT 51
#define MISSILE_A_CELLS 1
#define MISSILE_A_SIZE 51
#define MISSILE_C_HANDLE 5
#define MISSILE_C_WIDTH 19
#define MISSILE_C_HEIGHT 35
#define MISSILE_C_CELLS 1
#define MISSILE_C_SIZE 35
#define HELI_HANDLE 6
#define HELI_WIDTH 100
#define HELI_HEIGHT 62
#define HELI_CELLS 2
#define COPTER_FALL_HANDLE 7
#define COPTER_FALL_WIDTH 45
#define COPTER_FALL_HEIGHT 37
#define COPTER_FALL_CELLS 4
#define FIRE_HANDLE 8
#define FIRE_WIDTH 26
#define FIRE_HEIGHT 30
#define FIRE_CELLS 17
#define EXPLODE_BIG_HANDLE 9
#define EXPLODE_BIG_WIDTH 100
#define EXPLODE_BIG_HEIGHT 70
#define EXPLODE_BIG_CELLS 10
#define EXPLODE_BIG_SIZE 100
#define SOLDIER_RUN_HANDLE 10
#define SOLDIER_RUN_WIDTH 34
#define SOLDIER_RUN_HEIGHT 40
#define SOLDIER_RUN_CELLS 8
#define INFOFONT_HANDLE 11
#define INFOFONT_WIDTH 12
#define INFOFONT_HEIGHT 19
#define INFOFONT_CELLS 96
#define ASSETS_END 233032UL
static const shape_t BACKGROUND_COLOR_SHAPE = {0, 120, 68, 0};
static const shape_t BACKGROUND_BITS_SHAPE = {1, 480, 272, 0};
static const shape_t DEFENSOR_FRONT_SHAPE = {2, 104, 64, 0};
static const shape_t DEFENSOR_TURRET_SHAPE = {3, 38, 50, 50};
static const shape_t MISSILE_A_SHAPE = {4, 17, 51, 51};
static const shape_t MISSILE_C_SHAPE = {5, 19, 35, 35};
static const shape_t HELI_SHAPE = {6, 100, 62, 0};
static const shape_t COPTER_FALL_SHAPE = {7, 45, 37, 0};
static const shape_t FIRE_SHAPE = {8, 26, 30, 0};
static const shape_t EXPLODE_BIG_SHAPE = {9, 100, 70, 100};
static const shape_t SOLDIER_RUN_SHAPE = {10, 34, 40, 0};
static const shape_t INFOFONT_SHAPE = {11, 12, 19, 0};
