#define WELCOME_LOAD_ASSETS()  GD.safeload("nightw.gd2");
#define WELCOME_BACKGROUND_COLOR_HANDLE 0
#define WELCOME_BACKGROUND_COLOR_WIDTH 120
#define WELCOME_BACKGROUND_COLOR_HEIGHT 68
#define WELCOME_BACKGROUND_COLOR_CELLS 2
#define WELCOME_BACKGROUND_BITS_HANDLE 1
#define WELCOME_BACKGROUND_BITS_WIDTH 480
#define WELCOME_BACKGROUND_BITS_HEIGHT 272
#define WELCOME_BACKGROUND_BITS_CELLS 2
#define WELCOME_DISPLAYFONT_HANDLE 2
#define WELCOME_DISPLAYFONT_WIDTH 29
#define WELCOME_DISPLAYFONT_HEIGHT 46
#define WELCOME_DISPLAYFONT_CELLS 96
#define WELCOME_ASSETS_END 131668UL
static const shape_t WELCOME_BACKGROUND_COLOR_SHAPE = {0, 120, 68, 0};
static const shape_t WELCOME_BACKGROUND_BITS_SHAPE = {1, 480, 272, 0};
static const shape_t WELCOME_DISPLAYFONT_SHAPE = {2, 29, 46, 0};
